/**
 * NonUserMessage type definitions.
 *
 * Defines system-driven task pipeline interfaces for ChatAgent.
 * System-originated messages (scheduled tasks, A2A delegation, webhooks)
 * are routed to project-bound ChatAgent instances via NonUserMessageRouter.
 *
 * Issue #3331: NonUserMessage type definition (Phase 1 of RFC #3329).
 * Issue #3333: Scheduler integration with NonUserMessage (Phase 3).
 *
 * @module @disclaude/core/non-user-message
 */

// ============================================================================
// NonUserMessage
// ============================================================================

/**
 * Message type classification for system-driven messages.
 */
export type NonUserMessageType = 'scheduled' | 'a2a' | 'webhook' | 'system';

/**
 * Priority level for NonUserMessage queue ordering.
 */
export type NonUserMessagePriority = 'low' | 'normal' | 'high';

/**
 * System-originated message that is routed to a project-bound ChatAgent.
 *
 * Unlike user messages (which arrive via channel adapters), NonUserMessages
 * are generated by the system — e.g., scheduled tasks, agent-to-agent
 * delegation, webhook triggers, or admin commands.
 *
 * The message carries a `projectKey` which is resolved to a `chatId` via
 * project configuration lookup (IProjectRoutingProvider). The ChatAgent
 * bound to that chatId receives the payload through the existing
 * `processMessage()` flow.
 *
 * Design principle: NonUserMessage does NOT carry `chatId`. The chatId is
 * always resolved from `projectKey` via the routing provider, ensuring
 * single source of truth and preventing misrouting.
 */
export interface NonUserMessage {
  /** Unique message identifier (UUID) */
  id: string;
  /** Message type classification */
  type: NonUserMessageType;
  /** Origin source identifier (e.g., 'scheduler:daily-repo-maintenance', 'a2a:chat:oc_xxx') */
  source: string;
  /** Target project key (e.g., 'hs3180/disclaude'). Resolved to chatId via IProjectRoutingProvider. */
  projectKey: string;
  /** Free-form task instruction or structured data payload */
  payload: string;
  /** Priority for queue ordering within the project's queue */
  priority: NonUserMessagePriority;
  /** ISO 8601 timestamp when the message was created */
  createdAt: string;
}

// ============================================================================
// Routing Interfaces (Dependency Inversion)
// ============================================================================

/**
 * Resolved routing configuration for a project.
 *
 * Maps a `projectKey` to the concrete values needed to deliver
 * a message to the correct ChatAgent instance.
 */
export interface ProjectRoutingConfig {
  /** Project key (e.g., 'hs3180/disclaude') */
  key: string;
  /** Bound chat ID for the project's ChatAgent */
  chatId: string;
  /** Working directory for the project */
  workingDir: string;
  /** Optional model tier override for the project */
  modelTier?: string;
}

/**
 * Result of routing a NonUserMessage.
 */
export interface RouteResult {
  /** Whether routing succeeded */
  ok: boolean;
  /** Error message if routing failed */
  error?: string;
}

/**
 * Dependency inversion interface for project routing.
 *
 * Implemented by ProjectManager (or a wrapper) to provide
 * project-to-chatId resolution.
 */
export interface IProjectRoutingProvider {
  /**
   * Get routing configuration for a project.
   *
   * @param projectKey - Project key to look up
   * @returns Routing config if project exists, undefined otherwise
   */
  getRoutingConfig(projectKey: string): ProjectRoutingConfig | undefined;
}

/**
 * Dependency inversion interface for message delivery to ChatAgent.
 *
 * Implemented by AgentPool (or a wrapper) to deliver messages
 * to the correct ChatAgent instance.
 */
export interface IAgentMessageDelivery {
  /**
   * Check if the ChatAgent for a chatId is currently busy.
   *
   * @param chatId - Chat ID to check
   * @returns true if the agent is processing a message
   */
  isAgentBusy(chatId: string): boolean;

  /**
   * Deliver a message payload to the ChatAgent bound to a chatId.
   *
   * @param chatId - Target chat ID
   * @param payload - Message payload (task instruction)
   */
  deliverMessage(chatId: string, payload: string): void;
}

/**
 * NonUserMessageRouter interface.
 *
 * Routes NonUserMessages to the correct project-bound ChatAgent
 * via project config lookup → chatId resolution → message delivery.
 *
 * The router maintains per-project priority queues with configurable
 * backpressure (max queue size).
 */
export interface INonUserMessageRouter {
  /**
   * Route a NonUserMessage to the appropriate ChatAgent.
   *
   * @param message - The message to route
   * @returns Route result indicating success or failure
   */
  route(message: NonUserMessage): Promise<RouteResult>;
}
