// Regression guard for filebeat's log-collection globs (Issue #4777 / PR #4814).
//
// Why this file exists: PR #4814 shipped, and CI passed, with a filebeat path
// of `disclaude-combined.log.*` — the logrotate-style shape, where the
// sequence number is appended AFTER the extension. pino-roll does the
// opposite: it splits the trailing extension off and inserts the number
// BEFORE it (`disclaude-combined.1.log`). The two never intersect, so turning
// LOG_ROTATE=true silently stopped shipping logs to Elasticsearch, with every
// check green. Nothing in the suite connected the config file to the
// filenames the app actually produces.
//
// This test closes that loop from the config side: it reads the real
// filebeat.yml and asserts its globs against filenames generated by the real
// pino-roll. packages/core/src/utils/logger.test.ts covers the same contract
// from the producer side — that one would catch pino-roll changing its naming;
// this one catches someone editing the yaml back to a pattern that matches
// nothing.
//
// Scope notes (mirroring tests/launchd.test.ts):
//  - `npm run lint` only targets packages/*/src, so this file is NOT linted.
//  - coverage `include` covers only src/ and packages/ ts files, so this test
//    is NOT measured and cannot move the 70% thresholds.
//  - vitest `include` covers tests/**/*.test.ts.

import { describe, it, expect, afterAll } from 'vitest';
import { readFileSync, mkdtempSync, rmSync, globSync } from 'node:fs';
import { join, basename, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import pinoRoll from 'pino-roll';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CONTAINER_LOG_DIR = '/data/logs';

interface FilebeatConfig {
  'filebeat.inputs': Array<{ paths?: string[] }>;
}

function filebeatLogPaths(): string[] {
  const doc = yaml.load(readFileSync(join(REPO_ROOT, 'filebeat.yml'), 'utf8')) as FilebeatConfig;
  const paths = doc['filebeat.inputs']?.[0]?.paths;
  if (!paths) throw new Error('filebeat.yml: filebeat.inputs[0].paths is missing');
  return paths;
}

/**
 * Drive the real pino-roll until it has rolled, and return the filenames it
 * produced. No mocks — the whole point is to observe actual naming behaviour.
 */
async function rotatedFileNames(dir: string): Promise<string[]> {
  const dest = await pinoRoll({
    file: join(dir, 'disclaude-combined.log'),
    size: '1k',
    limit: { count: 2 },
    mkdir: true,
    symlink: true,
  });
  for (let i = 0; i < 400; i++) {
    dest.write(JSON.stringify({ i, pad: 'x'.repeat(80) }) + '\n');
  }
  await new Promise((r) => setTimeout(r, 400));
  return globSync(join(dir, '*')).map((p) => basename(p));
}

/** Apply a filebeat path (declared against /data/logs) to a local temp dir. */
function localize(pattern: string, dir: string): string {
  return join(dir, pattern.slice(CONTAINER_LOG_DIR.length + 1));
}

const dirs: string[] = [];
afterAll(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

function tmpLogDir(): string {
  const d = mkdtempSync(join(tmpdir(), 'filebeat-glob-'));
  dirs.push(d);
  return d;
}

describe('filebeat.yml log paths (#4777 / #4814)', () => {
  it('declares both the non-rotating path and a rotation glob', () => {
    const paths = filebeatLogPaths();
    expect(paths).toContain(`${CONTAINER_LOG_DIR}/disclaude-combined.log`);
    // Some pattern beyond the bare path must exist, or rotation ships nothing.
    expect(paths.filter((p) => p.includes('*')).length).toBeGreaterThan(0);
  });

  it('matches the filenames pino-roll actually writes', async () => {
    const dir = tmpLogDir();
    const produced = await rotatedFileNames(dir);

    // Sanity-check the fixture before asserting against it: if pino-roll did
    // not roll, an empty match below would be meaningless rather than a bug.
    expect(produced.filter((f) => /^disclaude-combined\.\d+\.log$/.test(f)).length)
      .toBeGreaterThan(0);

    const matched = new Set<string>();
    for (const p of filebeatLogPaths()) {
      for (const hit of globSync(localize(p, dir))) matched.add(basename(hit));
    }

    // Every rotated log must be picked up by at least one declared path.
    const rotated = produced.filter((f) => /^disclaude-combined\.\d+\.log$/.test(f));
    for (const f of rotated) {
      expect([...matched]).toContain(f);
    }
  });

  it('does not rely on the logrotate-style `.log.<n>` shape (the B1 bug)', async () => {
    const dir = tmpLogDir();
    const produced = await rotatedFileNames(dir);

    // pino-roll never emits this shape, so a config declaring only it collects
    // nothing. Pin the premise so the assertion below cannot pass vacuously.
    expect(produced.some((f) => /^disclaude-combined\.log\.\d+$/.test(f))).toBe(false);

    const wrong = globSync(join(dir, 'disclaude-combined.log.*'));
    expect(wrong).toEqual([]);

    // And the shipped config must not be the pattern that matches nothing.
    expect(filebeatLogPaths()).not.toContain(`${CONTAINER_LOG_DIR}/disclaude-combined.log.*`);
  });
});
