/**
 * Next Step Types - Type definitions for next-step recommendations.
 *
 * Issue #834: Refactor to use simple prompt instead of skill agent.
 * This module defines the types for next-step candidates that are
 * generated by LLM and passed to ChatAgent for display.
 */

/**
 * A single next-step recommendation candidate.
 */
export interface NextStepCandidate {
  /** Unique identifier for the candidate */
  id: string;
  /** Display text for the candidate */
  label: string;
  /** Optional description of what this action does */
  description?: string;
  /** Icon emoji for display */
  icon?: string;
  /** Category of the action (e.g., 'github', 'docs', 'test') */
  category?: string;
}

/**
 * Result of next-step recommendation generation.
 */
export interface NextStepResult {
  /** List of recommended next-step candidates */
  candidates: NextStepCandidate[];
  /** Summary of what was accomplished (for context) */
  taskSummary?: string;
  /** Detected task type */
  taskType?: string;
}
