/**
 * Loop Schedule Init - Initialize a loop schedule execution environment.
 *
 * Creates an isolated work directory with STATE.md, a Feishu group,
 * and records the mapping. Designed to be called by agents via npx tsx.
 *
 * Usage:
 *   LOOP_SLUG="research-ai-chips" \
 *   LOOP_TASK_DESCRIPTION="Research AI chip market trends" \
 *   LOOP_FREQUENCY="*/10 * * * *" \
 *   LOOP_USER_OPEN_ID="ou_xxx" \
 *   npx tsx skills/loop-schedule-init/loop-schedule-init.ts
 *
 * Issue #4004: Executable counterpart to the loop-schedule-init SKILL.md.
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

// ---- Types ----

interface MappingEntry {
  chatId: string;
  createdAt: string;
  purpose: string;
  workdir?: string;
  lastReminderAt?: string;
  reminderCount?: number;
}

interface MappingTable {
  [key: string]: MappingEntry;
}

interface InitResult {
  key: string;
  workdir: string;
  chatId: string;
  stateFile: string;
}

// ---- Config ----

const SCRIPT_DIR = path.dirname(new URL(import.meta.url).pathname);
const WORKSPACE_ROOT = path.resolve(SCRIPT_DIR, '../../..');
const MAPPING_FILE = process.env.MAPPING_FILE || path.join(WORKSPACE_ROOT, 'bot-chat-mapping.json');

// Required env vars
const SLUG = process.env.LOOP_SLUG || '';
const TASK_DESCRIPTION = process.env.LOOP_TASK_DESCRIPTION || '';
const FREQUENCY = process.env.LOOP_FREQUENCY || '*/10 * * * *';
const USER_OPEN_ID = process.env.LOOP_USER_OPEN_ID || '';

// Optional
const SCENE = process.env.LOOP_SCENE || 'generic';
const GROUP_NAME_PREFIX = process.env.LOOP_GROUP_NAME_PREFIX || 'Loop';

// ---- Helpers ----

function log(msg: string) {
  console.error(`[loop-schedule-init] ${msg}`);
}

function die(msg: string): never {
  console.error(`[loop-schedule-init] ERROR: ${msg}`);
  process.exit(1);
}

function validateSlug(slug: string): void {
  if (!slug) { die('LOOP_SLUG is required'); }
  if (!/^[a-z0-9][a-z0-9-]*$/.test(slug)) {
    die(`Invalid LOOP_SLUG "${slug}": must be lowercase alphanumeric with hyphens, no leading hyphen`);
  }
}

function slugToTitle(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function readMapping(): MappingTable {
  try {
    const content = fs.readFileSync(MAPPING_FILE, 'utf-8');
    const parsed = JSON.parse(content);
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      return parsed;
    }
    return {};
  } catch (e: any) {
    if (e.code === 'ENOENT') { return {}; }
    throw e;
  }
}

function writeMapping(table: MappingTable): void {
  const dir = path.dirname(MAPPING_FILE);
  fs.mkdirSync(dir, { recursive: true });
  const tmpFile = `${MAPPING_FILE}.${Date.now()}.tmp`;
  fs.writeFileSync(tmpFile, JSON.stringify(table, null, 2) + '\n', 'utf-8');
  fs.renameSync(tmpFile, MAPPING_FILE);
}

function findLarkCli(): string {
  const bin = 'lark-cli';
  try {
    const ver = execSync(`${bin} --version`, { stdio: 'pipe', encoding: 'utf-8' }).trim();
    log(`lark-cli found: ${ver}`);
    return bin;
  } catch {
    die('lark-cli not found. Ensure @larksuite/cli is installed.');
  }
}

// ---- Step Functions ----

/**
 * Step 1: Validate inputs.
 */
function validateInputs(): void {
  validateSlug(SLUG);
  if (!TASK_DESCRIPTION) { die('LOOP_TASK_DESCRIPTION is required'); }
}

/**
 * Step 2: Create isolated work directory.
 */
function createWorkdir(): string {
  const workdir = path.join(WORKSPACE_ROOT, `loop-${SLUG}`);
  if (fs.existsSync(workdir)) {
    die(`Work directory already exists: ${workdir}. Choose a different LOOP_SLUG or clean up first.`);
  }
  fs.mkdirSync(workdir, { recursive: true });
  log(`Created work directory: ${workdir}`);
  return workdir;
}

/**
 * Step 3: Initialize STATE.md with frontmatter.
 */
function initializeStateFile(workdir: string): string {
  const stateFile = path.join(workdir, 'STATE.md');
  const now = new Date().toISOString();

  const content = `---
status: active
phase: init
tickCount: 0
createdAt: "${now}"
updatedAt: "${now}"
slug: "${SLUG}"
scene: "${SCENE}"
frequency: "${FREQUENCY}"
task: "${TASK_DESCRIPTION.replace(/"/g, '\\"')}"
---

# Loop Task: ${slugToTitle(SLUG)}

${TASK_DESCRIPTION}

## Progress

- [ ] Phase 1: Initialization

## Notes

(Auto-generated by loop-schedule-init)
`;

  fs.writeFileSync(stateFile, content, 'utf-8');
  log(`Created STATE.md: ${stateFile}`);
  return stateFile;
}

/**
 * Step 4: Create Feishu group via lark-cli.
 */
function createFeishuGroup(larkCli: string): string {
  const groupName = `${GROUP_NAME_PREFIX}: ${slugToTitle(SLUG)}`;
  const groupDesc = `Loop schedule task: ${TASK_DESCRIPTION.slice(0, 100)}`;

  const args = [
    'im', '+chat-create',
    '--name', groupName,
    '--description', groupDesc,
  ];
  if (USER_OPEN_ID) {
    args.push('--users', USER_OPEN_ID);
  }

  const cmd = `${larkCli} ${args.map((a) => a.includes(' ') ? `"${a}"` : a).join(' ')}`;

  try {
    const result = execSync(cmd, { stdio: 'pipe', encoding: 'utf-8' });
    // Parse chat_id from JSON response
    const match = result.match(/"chat_id"\s*:\s*"([^"]+)"/);
    if (!match) {
      die(`Failed to parse chat_id from lark-cli output: ${result.slice(0, 200)}`);
    }
    const chatId = match[1];
    log(`Created Feishu group: ${chatId} (${groupName})`);
    return chatId;
  } catch (e: any) {
    const stderr = e.stderr?.toString() || e.message;
    die(`Failed to create Feishu group: ${stderr}`);
  }
}

/**
 * Step 5: Record mapping in bot-chat-mapping.json.
 */
function recordMapping(chatId: string, workdir: string): string {
  const key = `loop-${SLUG}`;
  const table = readMapping();

  if (table[key]) {
    log(`Warning: mapping key "${key}" already exists, overwriting`);
  }

  table[key] = {
    chatId,
    createdAt: new Date().toISOString(),
    purpose: 'loop-schedule',
    workdir,
  };

  writeMapping(table);
  log(`Recorded mapping: ${key} → ${chatId}`);
  return key;
}

// ---- Main ----

function main() {
  log('Initializing loop schedule environment...');

  // Step 1: Validate inputs
  validateInputs();

  // Step 2: Create work directory
  const workdir = createWorkdir();

  // Step 3: Initialize STATE.md
  const stateFile = initializeStateFile(workdir);

  // Step 4: Create Feishu group
  const larkCli = findLarkCli();
  const chatId = createFeishuGroup(larkCli);

  // Step 5: Record mapping
  const key = recordMapping(chatId, workdir);

  // Summary output (JSON to stdout for programmatic consumption)
  const result: InitResult = { key, workdir, chatId, stateFile };
  console.log(JSON.stringify(result, null, 2));

  log(`Loop schedule environment initialized successfully.`);
  log(`  Key: ${key}`);
  log(`  Chat: ${chatId}`);
  log(`  Workdir: ${workdir}`);
  log(`  State: ${stateFile}`);
  log(``);
  log(`Next steps (to be done by agent):`);
  log(`  1. Create SCHEDULE.md in ${workdir}`);
  log(`  2. Inject system prompt via push_to_agent to ${chatId}`);
  log(`  3. Register schedule task with frequency "${FREQUENCY}"`);
}

main();
