/**
 * Task Suggestion Service - Generates interactive suggestion cards after task completion.
 *
 * Issue #470: Task completion follow-up suggestions
 *
 * Unlike rule-based approaches, this service uses LLM to analyze task context
 * and generate relevant follow-up suggestions dynamically.
 *
 * Key design decisions based on user feedback:
 * 1. Use interactive card buttons (not text suggestions)
 * 2. Generate suggestions from context analysis (not pre-defined prompts)
 * 3. Minimize user interaction burden
 */

import { getProvider } from '../sdk/index.js';
import type { IAgentSDKProvider } from '../sdk/interface.js';
import { Config } from '../config/index.js';
import { createLogger } from '../utils/logger.js';
import {
  buildCard,
  buildDivider,
  buildActionGroup,
  buildButton,
  type BuiltCard,
  type ButtonAction,
} from '../platforms/feishu/card-builders/interactive-card-builder.js';

const logger = createLogger('TaskSuggestion');

/**
 * A single suggestion generated by LLM.
 */
export interface Suggestion {
  /** Emoji icon for the suggestion */
  emoji: string;
  /** Short description (shown on button) */
  description: string;
  /** Prompt to send to Agent when clicked */
  prompt: string;
}

/**
 * Task suggestion configuration.
 */
export interface TaskSuggestionConfig {
  /** Enable/disable suggestion feature */
  enabled?: boolean;
  /** Maximum number of suggestions to show (default: 4) */
  maxSuggestions?: number;
}

/**
 * Context for generating suggestions.
 */
export interface SuggestionContext {
  /** Original user message that started the task */
  userMessage: string;
  /** Agent's result content */
  resultContent: string;
  /** Chat ID for context */
  chatId?: string;
}

/**
 * Action value for suggestion button clicks.
 * This is serialized as JSON in the button's value field.
 */
export interface SuggestionActionValue {
  /** Action type: 'suggestion' */
  action: 'suggestion';
  /** The prompt to send to the Agent */
  prompt: string;
  /** The description of the suggestion (for logging) */
  description: string;
}

/**
 * System prompt for the suggestion generator.
 * Instructs the LLM to analyze context and generate relevant suggestions.
 */
const SUGGESTION_SYSTEM_PROMPT = `你是一个任务分析助手。当用户完成一个任务后，你需要根据任务内容分析接下来用户可能想要做什么。

## 输出要求

你必须输出一个 JSON 数组，包含 2-4 个建议。每个建议包含：
- emoji: 一个表情符号
- description: 简短的中文描述（不超过10个字）
- prompt: 用户点击后发送给 Agent 的完整指令

## 分析原则

1. **基于上下文**: 建议必须与刚才完成的任务直接相关
2. **自然延续**: 建议应该是任务的合理下一步
3. **具体可执行**: prompt 必须是具体、可执行的指令
4. **多样性**: 建议应该覆盖不同类型的后续操作

## 常见任务类型的后续操作

- 代码分析 → 生成文档、检查问题、重构优化
- 代码修改 → 运行测试、提交更改、创建 PR
- Bug修复 → 验证修复、添加测试、更新日志
- 文件操作 → 检查结果、继续处理、清理工作
- 信息查询 → 深入分析、保存结果、分享信息
- 测试执行 → 修复失败、生成报告、增加覆盖

## 示例

用户消息: 帮我分析 src 目录的代码结构
Agent结果: 分析完成，src 目录包含 agents/、channels/、config/ 等模块...

输出:
\`\`\`json
[
  {"emoji": "📝", "description": "生成结构文档", "prompt": "请为刚才分析的代码结构生成一份 Markdown 文档"},
  {"emoji": "🔍", "description": "检查代码问题", "prompt": "请检查 src 目录下的代码是否有潜在问题"},
  {"emoji": "📊", "description": "统计代码行数", "prompt": "请统计 src 目录下各模块的代码行数和文件数量"}
]
\`\`\`

只输出 JSON 数组，不要输出其他内容。`;

/**
 * Task Suggestion Service - Generates follow-up suggestions after task completion.
 *
 * This service uses LLM to analyze task context and generate relevant suggestions.
 */
export class TaskSuggestionService {
  private readonly config: Required<TaskSuggestionConfig>;
  private readonly sdkProvider: IAgentSDKProvider;

  constructor(config?: TaskSuggestionConfig) {
    this.config = {
      enabled: config?.enabled ?? true,
      maxSuggestions: config?.maxSuggestions ?? 4,
    };
    this.sdkProvider = getProvider(); // Use default provider
    logger.info({ config: this.config }, 'TaskSuggestionService initialized');
  }

  /**
   * Check if suggestions are enabled.
   */
  isEnabled(): boolean {
    return this.config.enabled;
  }

  /**
   * Generate suggestions using LLM analysis.
   *
   * @param context - The suggestion context (user message + result)
   * @returns Array of suggestions, or empty array if generation fails
   */
  async generateSuggestions(context: SuggestionContext): Promise<Suggestion[]> {
    const userPrompt = `## 用户消息
${context.userMessage}

## Agent 执行结果
${context.resultContent}

请分析上述任务并生成 2-4 个合理的后续操作建议。`;

    try {
      logger.debug({ chatId: context.chatId }, 'Generating suggestions via LLM');

      // Combine system prompt with user prompt in the input
      const fullPrompt = `${SUGGESTION_SYSTEM_PROMPT}

---

${userPrompt}`;

      // Use queryOnce for a one-shot LLM call
      const iterator = this.sdkProvider.queryOnce(
        fullPrompt,
        {
          model: Config.getAgentConfig().model,
          settingSources: ['task-suggestion'],
        }
      );

      // Collect all messages from the iterator
      let textContent = '';
      for await (const message of iterator) {
        if (message.type === 'result' && message.content) {
          textContent = message.content;
          break; // Get the first result message
        }
      }

      // Parse JSON from response
      const suggestions = this.parseSuggestions(textContent);

      logger.info(
        { chatId: context.chatId, suggestionCount: suggestions.length },
        'Generated suggestions via LLM'
      );

      return suggestions.slice(0, this.config.maxSuggestions);
    } catch (error) {
      logger.error({ err: error, chatId: context.chatId }, 'Failed to generate suggestions');
      return [];
    }
  }

  /**
   * Parse suggestions from LLM response.
   * Handles various formats and extracts JSON array.
   */
  private parseSuggestions(response: string): Suggestion[] {
    try {
      // Try to extract JSON from markdown code block
      const jsonMatch = response.match(/```(?:json)?\s*([\s\S]*?)```/);
      const jsonStr = jsonMatch ? jsonMatch[1].trim() : response.trim();

      const parsed = JSON.parse(jsonStr);

      if (!Array.isArray(parsed)) {
        logger.warn({ response }, 'LLM response is not an array');
        return [];
      }

      // Validate and filter suggestions
      const suggestions: Suggestion[] = [];
      for (const item of parsed) {
        if (
          typeof item === 'object' &&
          item !== null &&
          typeof item.emoji === 'string' &&
          typeof item.description === 'string' &&
          typeof item.prompt === 'string'
        ) {
          suggestions.push({
            emoji: item.emoji,
            description: item.description,
            prompt: item.prompt,
          });
        }
      }

      return suggestions;
    } catch (parseError) {
      logger.warn({ parseError, response }, 'Failed to parse LLM response as JSON');
      return [];
    }
  }

  /**
   * Build an interactive card from suggestions.
   *
   * @param suggestions - Array of suggestions
   * @returns Built card object, or null if no suggestions
   */
  buildSuggestionCard(suggestions: Suggestion[]): BuiltCard | null {
    if (suggestions.length === 0) {
      return null;
    }

    // Create buttons from suggestions
    const buttons: ButtonAction[] = suggestions.map((s) =>
      buildButton({
        text: `${s.emoji} ${s.description}`,
        value: JSON.stringify({
          action: 'suggestion',
          prompt: s.prompt,
          description: s.description,
        } as SuggestionActionValue),
      })
    );

    // Create card with title, divider, and action buttons
    const card = buildCard({
      header: {
        title: '💡 接下来你可以',
        template: 'blue',
      },
      elements: [
        buildDivider(),
        // Add buttons as action groups (2 per row for better mobile experience)
        ...this.groupButtons(buttons),
      ],
    });

    return card;
  }

  /**
   * Group buttons into action groups (2 per row).
   */
  private groupButtons(buttons: ButtonAction[]): ReturnType<typeof buildActionGroup>[] {
    const groups: ReturnType<typeof buildActionGroup>[] = [];

    for (let i = 0; i < buttons.length; i += 2) {
      const rowButtons = buttons.slice(i, i + 2);
      groups.push(buildActionGroup(rowButtons));
    }

    return groups;
  }

  /**
   * Generate and build suggestion card from context.
   * This is the main entry point for generating suggestions.
   *
   * @param context - The suggestion context
   * @returns Built card object, or null if no suggestions or disabled
   */
  async generateSuggestionCard(context: SuggestionContext): Promise<BuiltCard | null> {
    if (!this.config.enabled) {
      return null;
    }

    const suggestions = await this.generateSuggestions(context);
    return this.buildSuggestionCard(suggestions);
  }
}

// ============================================================================
// Global Instance Management
// ============================================================================

let globalTaskSuggestionService: TaskSuggestionService | null = null;

/**
 * Initialize the global task suggestion service.
 */
export function initTaskSuggestionService(config?: TaskSuggestionConfig): TaskSuggestionService {
  globalTaskSuggestionService = new TaskSuggestionService(config);
  logger.info('Global TaskSuggestionService initialized');
  return globalTaskSuggestionService;
}

/**
 * Get the global task suggestion service.
 * Returns null if not initialized (suggestions disabled).
 */
export function getTaskSuggestionService(): TaskSuggestionService | null {
  return globalTaskSuggestionService;
}

/**
 * Reset the global task suggestion service (for testing).
 */
export function resetTaskSuggestionService(): void {
  globalTaskSuggestionService = null;
}

/**
 * Check if an action value is a suggestion action.
 */
export function isSuggestionAction(value: unknown): value is SuggestionActionValue {
  if (typeof value !== 'object' || value === null) {
    return false;
  }
  const v = value as Record<string, unknown>;
  return v.action === 'suggestion' && typeof v.prompt === 'string';
}
